name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'uno'
          - 'leonardo'
          - 'mega2560'
          - 'esp8266'
          - 'esp32'
          - 'trinket_m0'
          - 'cpb'
          - 'cpx'
          - 'metro_m0'
          - 'metro_m4_tinyusb'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install SDFat
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/adafruit/SdFat.git /home/runner/Arduino/libraries/SdFat
        git clone --quiet https://github.com/adafruit/Adafruit_SPIFlash.git /home/runner/Arduino/libraries/Adafruit_SPIFlash

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

  clang_and_doxy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit E-Paper Display Library"
      run: bash ci/doxy_gen_and_deploy.sh
